/* Generated By:JavaCC: Do not edit this line. as2j.java */
  package jason.asSyntax.parser;

  import java.util.*;
  import java.io.*;
  import java.util.logging.*;

  import jason.*;
  import jason.asSemantics.*;
  import jason.bb.*;
  import jason.asSyntax.*;
  import jason.asSyntax.directives.*;
  import jason.asSyntax.ArithExpr.ArithmeticOp;
  import jason.asSyntax.LogExpr.LogicalOp;
  import jason.asSyntax.RelExpr.RelationalOp;
  import jason.asSyntax.PlanBody.BodyType;
  import jason.asSyntax.Trigger.TEOperator;
  import jason.asSyntax.Trigger.TEType;
  import jason.jeditplugin.*;

  public class as2j implements as2jConstants {
    private String asSource = null;
    private Agent  curAg    = null;

    private static Logger logger = Logger.getLogger("aslparser");
    private static Set<String> parsedFiles = new HashSet<String>();
    private static Config config = Config.get(false);

    public void setAg(Agent ag) { curAg = ag; }

    private String getSourceRef(SourceInfo s) {
        if (s == null)
            return "[]";
        else
            return "["+s.getSrcFile()+":"+s.getBeginSrcLine()+"]";
    }
    private String getSourceRef(DefaultTerm t) {
        return getSourceRef( t.getSrcInfo());
    }
    private String getSourceRef(Object t) {
        if (t instanceof DefaultTerm)
            return getSourceRef((DefaultTerm)t);
        else if (t instanceof SourceInfo)
            return getSourceRef((SourceInfo)t);
        else
            return "[]";
    }

        private InternalActionLiteral checkInternalActionsInContext(LogicalFormula f, Agent ag) throws Exception {
            if (f != null) {
                if (f instanceof InternalActionLiteral) {
                    InternalActionLiteral ial = (InternalActionLiteral)f;
                    if (! ial.getIA(ag).canBeUsedInContext())
                       return ial;
                } else if (f instanceof LogExpr) {
                    LogExpr le = (LogExpr)f;
                    InternalActionLiteral ial = checkInternalActionsInContext(le.getLHS(), ag);
                    if (ial != null)
                        return ial;
                    if (!le.isUnary())
                        return checkInternalActionsInContext(le.getRHS(), ag);
                }
        }
        return null;
    }

    private ArithFunction getArithFunction(Literal l) {
        ArithFunction af = null;
        if (curAg != null)
           // try to find the function in agent register
           af = curAg.getFunction(l.getFunctor(), l.getArity());
        if (af == null)
           // try global function
           af = FunctionRegister.getFunction(l.getFunctor(), l.getArity());
        return af;
    }

    private Term changeToAtom(Object o) {
        Term u = (Term)o;
        if (u.isAtom()) {
           return new Atom((Literal)u);
        } else {
           return u;
        }
    }

/* AgentSpeak Grammar */

/*   agent ::= bels goals plans

     returns true if achieved the end of file
     returns false if achieved a "{ end }" directive  
*/
  final public boolean agent(Agent a) throws ParseException, jason.JasonException {
                                Literal b;
                                Literal g;
                                Plan    p;
                                curAg = a;
                                if (a != null && a.getASLSrc() != null) asSource = a.getASLSrc();
                                boolean endDir = false;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 30:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      endDir = directive(a);
                                if (endDir) {if (true) return false;}
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TK_TRUE:
      case TK_FALSE:
      case TK_NEG:
      case TK_BEGIN:
      case TK_END:
      case ATOM:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      b = belief();
                                if (a != null) a.addInitialBel(b);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 30:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_3;
        }
        endDir = directive(a);
                                if (endDir) {if (true) return false;}
      }
    }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_4;
      }
      g = initial_goal();
                                if (a != null) a.addInitialGoal(g);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 30:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_5;
        }
        endDir = directive(a);
                                if (endDir) {if (true) return false;}
      }
    }
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TK_LABEL_AT:
      case 37:
      case 38:
      case 39:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_6;
      }
      p = plan();
                                if (a != null) {
                                   a.getPL().add(p);
                                   // warning only not parsed files
                                   if (config.getBoolean(Config.WARN_SING_VAR) && !parsedFiles.contains(asSource)) {
                                      List<VarTerm> singletonVars = p.getSingletonVars();
                                      if (singletonVars.size() > 0) {
                                         logger.warning(getSourceRef(p.getSrcInfo())+" warning: the plan for event '"+p.getTrigger()+"' has the following singleton variables: "+singletonVars);
                                      }
                                   }
                                }
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case TK_TRUE:
        case TK_FALSE:
        case TK_NEG:
        case TK_BEGIN:
        case TK_END:
        case ATOM:
          ;
          break;
        default:
          jj_la1[6] = jj_gen;
          break label_7;
        }
        b = belief();
                                if (a != null) {
                                  if (b.isRule()) {
                                      a.addInitialBel(b);
                                      //if (!parsedFiles.contains(asSource))
                                      //   logger.warning(getSourceRef(b)+" warning: avoid to mix rules and plans ('"+b+"').");
                                  } else {
                                      {if (true) throw new ParseException(getSourceRef(b)+" The belief '"+b+"' is not in the begin of the source code!");}
                                  }
                                }
      }
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 30:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_8;
        }
        endDir = directive(a);
                                if (endDir) {if (true) return false;}
      }
    }
    jj_consume_token(0);
                                if (a != null) parsedFiles.add(a.getASLSrc());
                                {if (true) return true;}
    throw new Error("Missing return statement in function");
  }

/* Directive 

   returns true if the directive is "{ end }", false otherwise
*/
  final public boolean directive(Agent outerAg) throws ParseException, jason.JasonException {
                                Pred dir = null;
                                Agent resultOfDirective = null;
                                Agent bakAg = curAg;
                                boolean isEOF = false;
    jj_consume_token(30);
    if (jj_2_1(4)) {
      jj_consume_token(TK_BEGIN);
      dir = pred();
      jj_consume_token(31);
                                Agent innerAg = new Agent(); innerAg.initAg();
      isEOF = agent(innerAg);
                                if (isEOF)
                                   {if (true) throw new ParseException(getSourceRef(dir)+" The directive '{ begin "+dir+"}' does not end with '{ end }'.");}
                                else
                                   resultOfDirective = DirectiveProcessor.process(dir, outerAg, innerAg);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TK_BEGIN:
      case TK_END:
      case ATOM:
        dir = pred();
        jj_consume_token(31);
                                if (dir.toString().equals("end"))
                                   {if (true) return true;}
                                else
                                   resultOfDirective = DirectiveProcessor.process(dir, outerAg, null);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                                if (resultOfDirective != null && outerAg != null) {
                                  // import bels, plans and initial goals from agent resultOfDirective
                                  outerAg.importComponents(resultOfDirective);
                                }
                                curAg = bakAg;
                                {if (true) return false;}
    throw new Error("Missing return statement in function");
  }

/* Beliefs & Rules */
  final public Literal belief() throws ParseException {
                     Literal h; Object t;
    h = literal();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 32:
      jj_consume_token(32);
      t = log_expr();
                               h = new Rule(h,(LogicalFormula)t);
                               // warning only not parsed files
                               if (config.getBoolean(Config.WARN_SING_VAR) && !parsedFiles.contains(asSource)) {
                                  List<VarTerm> singletonVars = h.getSingletonVars();
                                  if (singletonVars.size() > 0) {
                                     logger.warning(getSourceRef(h)+" warning: the rule with head '"+((Rule)h).headClone()+"' has the following singleton variables: "+singletonVars);
                                  }
                               }
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(33);
                               {if (true) return h;}
    throw new Error("Missing return statement in function");
  }

/* Initial goals */
  final public Literal initial_goal() throws ParseException {
                           Literal g;
    jj_consume_token(34);
    g = literal();
    jj_consume_token(33);
                           {if (true) return g;}
    throw new Error("Missing return statement in function");
  }

/* Plan */
  final public Plan plan() throws ParseException {
                        Token k;
                        Pred L = null;
                        Trigger T;
                        Object C = null;
                        PlanBody B = null;
                        int start = -1, end;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TK_LABEL_AT:
      k = jj_consume_token(TK_LABEL_AT);
      L = pred();
                                    start = k.beginLine;
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    T = trigger();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 35:
      k = jj_consume_token(35);
      C = log_expr();
                                   if (start == -1) start = k.beginLine;
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 36:
      k = jj_consume_token(36);
      B = plan_body();
                                   if (start == -1) start = k.beginLine;
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    k = jj_consume_token(33);
                                   if (start == -1) start = k.beginLine;
                     end = k.beginLine;
                     InternalActionLiteral ial = null;
                     try { ial = checkInternalActionsInContext((LogicalFormula)C, curAg); } catch (Exception e) {}
                     if (ial != null)
                        {if (true) throw new ParseException(getSourceRef(ial)+" The internal action '"+ial+"' can not be used in plan's context!");}
                         if (B != null && B.getBodyTerm().equals(Literal.LTrue))
                            B = (PlanBody)B.getBodyNext();
                     Plan p = new Plan(L,T,(LogicalFormula)C, B);
                     p.setSrcInfo(new SourceInfo(asSource,start,end));
                     {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

/* Trigger */
  final public Trigger trigger() throws ParseException {
                        TEOperator teOp;
                                TEType     teType = TEType.belief;
                                        Literal F;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 37:
      jj_consume_token(37);
                 teOp = TEOperator.add;
      break;
    case 38:
      jj_consume_token(38);
                 teOp = TEOperator.del;
      break;
    case 39:
      jj_consume_token(39);
                 teOp = TEOperator.goalState;
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 34:
    case 40:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
        jj_consume_token(34);
                 teType = TEType.achieve;
        break;
      case 40:
        jj_consume_token(40);
                 teType = TEType.test;
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TK_TRUE:
    case TK_FALSE:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case ATOM:
      F = literal();
      break;
    case VAR:
    case UNNAMEDVAR:
      F = var();
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                 {if (true) return new Trigger(teOp,teType,F);}
    throw new Error("Missing return statement in function");
  }

/* Plan body */
  final public PlanBody plan_body() throws ParseException {
                             Object F; PlanBody R = null; boolean hasPV = false; boolean isControl = true;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TK_IF:
      F = stmtIF();
      break;
    case TK_FOR:
      F = stmtFOR();
      break;
    case TK_WHILE:
      F = stmtWHILE();
      break;
    case VAR:
    case TK_TRUE:
    case TK_FALSE:
    case TK_NOT:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case NUMBER:
    case STRING:
    case ATOM:
    case UNNAMEDVAR:
    case 34:
    case 37:
    case 38:
    case 40:
    case 42:
    case 44:
      F = body_formula();
                             isControl = false; if (!(F instanceof PlanBody)) {if (true) throw new ParseException(getSourceRef(F)+" "+F+" is not a body literal!");}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 41:
      jj_consume_token(41);
                             hasPV = true;
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
    case TK_TRUE:
    case TK_FALSE:
    case TK_NOT:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case TK_IF:
    case TK_FOR:
    case TK_WHILE:
    case NUMBER:
    case STRING:
    case ATOM:
    case UNNAMEDVAR:
    case 34:
    case 37:
    case 38:
    case 40:
    case 42:
    case 44:
      R = plan_body();
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
                             if (R != null) {
                                if (!isControl && !hasPV) {
                                     {if (true) throw new ParseException(getSourceRef(F)+" Expected ';' after '"+F+"'.");}
                                }
                                ((PlanBody)F).setBodyNext( R );
                             }

                             {if (true) return (PlanBody)F;}
    throw new Error("Missing return statement in function");
  }

  final public PlanBody stmtIF() throws ParseException {
                         Object B; Term T1; Term T2 = null; Literal stmtLiteral; boolean useElse = false;
    jj_consume_token(TK_IF);
    jj_consume_token(42);
    B = log_expr();
    jj_consume_token(43);
    T1 = plan_term();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TK_ELSE:
    case 30:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TK_ELSE:
        jj_consume_token(TK_ELSE);
                         useElse = true;
        break;
      default:
        jj_la1[20] = jj_gen;
        ;
      }
      T2 = plan_term();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
                         try {
                            if (T2 == null) {
                                stmtLiteral = new InternalActionLiteral(ASSyntax.createStructure(".if_then_else", (Term)B, T1), curAg);
                                stmtLiteral.setSrcInfo( ((Term)B).getSrcInfo() );
                            } else {
                                stmtLiteral = new InternalActionLiteral(ASSyntax.createStructure(".if_then_else", (Term)B, T1, T2), curAg);
                                stmtLiteral.setSrcInfo( ((Term)B).getSrcInfo() );
                                if (! useElse) {
                                   logger.warning(getSourceRef(stmtLiteral)+" warning: use keyword 'else' before the else part of if.");
                                }
                            }
                            {if (true) return new PlanBodyImpl(BodyType.internalAction, stmtLiteral);}
                         } catch (Exception e) {
                            e.printStackTrace();
                         }
    throw new Error("Missing return statement in function");
  }

  final public PlanBody stmtFOR() throws ParseException {
                         Object B; Term T1; Literal stmtLiteral;
    jj_consume_token(TK_FOR);
    jj_consume_token(42);
    B = log_expr();
    jj_consume_token(43);
    T1 = plan_term();
                         try {
                            stmtLiteral = new InternalActionLiteral(ASSyntax.createStructure(".foreach", (Term)B, T1), curAg);
                            stmtLiteral.setSrcInfo( ((Term)B).getSrcInfo() );
                            {if (true) return new PlanBodyImpl(BodyType.internalAction, stmtLiteral);}
                         } catch (Exception e) {
                            e.printStackTrace();
                         }
    throw new Error("Missing return statement in function");
  }

  final public PlanBody stmtWHILE() throws ParseException {
                         Object B; Term T1; Literal stmtLiteral;
    jj_consume_token(TK_WHILE);
    jj_consume_token(42);
    B = log_expr();
    jj_consume_token(43);
    T1 = plan_term();
                         try {
                            stmtLiteral = new InternalActionLiteral(ASSyntax.createStructure(".loop", (Term)B, T1), curAg);
                            stmtLiteral.setSrcInfo( ((Term)B).getSrcInfo() );
                            {if (true) return new PlanBodyImpl(BodyType.internalAction, stmtLiteral);}
                         } catch (Exception e) {
                            e.printStackTrace();
                         }
    throw new Error("Missing return statement in function");
  }

  final public Object body_formula() throws ParseException {
                         BodyType formType = BodyType.action;  Object B;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 34:
    case 37:
    case 38:
    case 40:
    case 44:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
        jj_consume_token(34);
                         formType = BodyType.achieve;
        break;
      case 44:
        jj_consume_token(44);
                         formType = BodyType.achieveNF;
        break;
      case 40:
        jj_consume_token(40);
                         formType = BodyType.test;
        break;
      case 37:
        jj_consume_token(37);
                         formType = BodyType.addBel;
        break;
      case 38:
        jj_consume_token(38);
                         formType = BodyType.delBel;
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 37:
          jj_consume_token(37);
                         formType = BodyType.delAddBel;
          break;
        default:
          jj_la1[22] = jj_gen;
          ;
        }
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    B = log_expr();
                         if (formType == BodyType.action && B instanceof RelExpr) {
                            {if (true) return new PlanBodyImpl(BodyType.constraint, (RelExpr)B);} // constraint
                         } else if (B instanceof Literal) {
                            if ( ((Literal)B).isInternalAction() )
                               formType = BodyType.internalAction;
                            {if (true) return new PlanBodyImpl(formType, (Literal)B);}
                         } else {
                                if (formType == BodyType.test) {
                                   if (B instanceof LogicalFormula)
                                      {if (true) return new PlanBodyImpl(BodyType.test, (Term)B);}  // used in ?(a & b)
                                   else
                                      {if (true) throw new ParseException(getSourceRef(B)+" The argument for ? is not a logical formula.");}
                                } else {
                               {if (true) return B;}
                                }
                         }
    throw new Error("Missing return statement in function");
  }

  final public Term plan_term() throws ParseException {
                               Trigger T = null; Object C = null; PlanBody B = null, B1 = null; Plan P = null; boolean pb = true; Pred L = null;
    jj_consume_token(30);
    if (jj_2_2(4)) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TK_LABEL_AT:
        jj_consume_token(TK_LABEL_AT);
        L = pred();
                              pb = false;
        break;
      default:
        jj_la1[25] = jj_gen;
        ;
      }
      T = trigger();
                              if (T.getType() != TEType.belief) pb = false;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 35:
        jj_consume_token(35);
        C = log_expr();
                              pb = false;
        break;
      default:
        jj_la1[26] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 36:
      case 41:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 36:
          jj_consume_token(36);
                              pb = false;
          break;
        case 41:
          jj_consume_token(41);
                              if (!pb) {if (true) throw new ParseException(getSourceRef(T)+" Wrong place for ';'");}
          break;
        default:
          jj_la1[27] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[28] = jj_gen;
        ;
      }
    } else {
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
    case TK_TRUE:
    case TK_FALSE:
    case TK_NOT:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case TK_IF:
    case TK_FOR:
    case TK_WHILE:
    case NUMBER:
    case STRING:
    case ATOM:
    case UNNAMEDVAR:
    case 34:
    case 37:
    case 38:
    case 40:
    case 42:
    case 44:
      B = plan_body();
      break;
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(31);
                             if (T != null) {
                                // handle the case of "+a1", parsed as TE, need to be changed to plan's body
                                // handle the case of "+a1; +a2", parsed as "TE; Body"
                                if (pb && L == null) {
                                  if (T.isAddition())
                                     B1 = new PlanBodyImpl(BodyType.addBel, T.getLiteral());
                                  else
                                     B1 = new PlanBodyImpl(BodyType.delBel, T.getLiteral());
                                  B1.setAsBodyTerm(true);
                                  if (B != null)
                                     B1.setBodyNext(B);
                                  {if (true) return B1;}
                                }
                                if (C == null && B == null && L == null) {
                                    // handle the case of a single trigger
                                    T.setAsTriggerTerm(true);
                                    {if (true) return T;}
                                } else {
                                    // handle the case of a entire plan
                                    Plan p = new Plan(L,T,(LogicalFormula)C, B);
                                    p.setSrcInfo(T.getSrcInfo());
                                    p.setAsPlanTerm(true);
                                    {if (true) return p;}
                                }
                             }

                             // the case of a simple plan body term
                             if (B == null)
                                B = new PlanBodyImpl();
                             B.setAsBodyTerm(true);

                             {if (true) return B;}
    throw new Error("Missing return statement in function");
  }

/* Literal */
  final public Literal literal() throws ParseException {
                                Pred F; Token k; boolean type = Literal.LPos;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case ATOM:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TK_NEG:
        jj_consume_token(TK_NEG);
                                type = Literal.LNeg;
        break;
      default:
        jj_la1[30] = jj_gen;
        ;
      }
      F = pred();
                                if (F.getFunctor().indexOf(".") >= 0) {
                                   if (F.hasAnnot())
                                      {if (true) throw new ParseException(getSourceRef(F)+" Internal actions cannot have annotations.");}
                                   if (type == Literal.LNeg)
                                      {if (true) throw new ParseException(getSourceRef(F)+" Internal actions cannot be negated.");}
                                                                   try {
                                                                      {if (true) return new InternalActionLiteral(F, curAg);}
                                   } catch (Exception e) {
                                      if (getArithFunction(F) == null) // it is not a registered function
                                         logger.warning(getSourceRef(F)+" warning: The internal action class for '"+F+"' was not loaded! Error: "+e);
                                   }
                                }
                                {if (true) return new LiteralImpl(type,F);}
      break;
    case TK_TRUE:
      k = jj_consume_token(TK_TRUE);
                                {if (true) return Literal.LTrue;}
      break;
    case TK_FALSE:
      k = jj_consume_token(TK_FALSE);
                                {if (true) return Literal.LFalse;}
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/* Annotated Formulae */
  final public Pred pred() throws ParseException {
                        Token K; Pred p; List l; ListTerm lt; Term b;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ATOM:
      K = jj_consume_token(ATOM);
      break;
    case TK_BEGIN:
      K = jj_consume_token(TK_BEGIN);
      break;
    case TK_END:
      K = jj_consume_token(TK_END);
      break;
    default:
      jj_la1[32] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                         p = new Pred(K.image);
                         p.setSrcInfo(new SourceInfo(asSource, K.beginLine));
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 42:
      jj_consume_token(42);
      l = terms();
      jj_consume_token(43);
                         p.setTerms(l);
      break;
    default:
      jj_la1[33] = jj_gen;
      ;
    }
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 30:
        ;
        break;
      default:
        jj_la1[34] = jj_gen;
        break label_9;
      }
      b = plan_term();
                         p.addTerm(b);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 46:
      lt = list();
                         p.setAnnots(lt);
      break;
    default:
      jj_la1[35] = jj_gen;
      ;
    }
                         {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

/* List of terms */
  final public List terms() throws ParseException {
                    ArrayList listTerms = new ArrayList(); Term v; PlanBody o;
    v = term();
                         listTerms.add(v);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 45:
        ;
        break;
      default:
        jj_la1[36] = jj_gen;
        break label_10;
      }
      jj_consume_token(45);
      v = term();
                         listTerms.add(v);
    }
                         listTerms.trimToSize();
                         {if (true) return listTerms;}
    throw new Error("Missing return statement in function");
  }

  final public Term term() throws ParseException {
                         Object o;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 46:
      o = list();
      break;
    case 30:
      o = plan_term();
      break;
    case VAR:
    case TK_TRUE:
    case TK_FALSE:
    case TK_NOT:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case NUMBER:
    case STRING:
    case ATOM:
    case UNNAMEDVAR:
    case 38:
    case 42:
      o = log_expr();
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                         {if (true) return changeToAtom(o);}
    throw new Error("Missing return statement in function");
  }

  final public ListTermImpl list() throws ParseException {
                            ListTermImpl lt = new ListTermImpl(); ListTerm last; Token K; Term f;
    jj_consume_token(46);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
    case TK_TRUE:
    case TK_FALSE:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case NUMBER:
    case STRING:
    case ATOM:
    case UNNAMEDVAR:
    case 30:
    case 38:
    case 42:
    case 46:
      f = term_in_list();
                            last = lt.append(f); lt.setSrcInfo(f.getSrcInfo());
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 45:
          ;
          break;
        default:
          jj_la1[38] = jj_gen;
          break label_11;
        }
        jj_consume_token(45);
        f = term_in_list();
                            last = last.append(f);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 47:
        jj_consume_token(47);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VAR:
          K = jj_consume_token(VAR);
                            last.setNext(new VarTerm(K.image));
          break;
        case UNNAMEDVAR:
          K = jj_consume_token(UNNAMEDVAR);
                            last.setNext(new UnnamedVar(K.image));
          break;
        case 46:
          f = list();
                            last = last.concat((ListTerm)f);
          break;
        default:
          jj_la1[39] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[40] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[41] = jj_gen;
      ;
    }
    jj_consume_token(48);
                            {if (true) return lt;}
    throw new Error("Missing return statement in function");
  }

// term_in_list is the same as term, but log_expr/plan_body must be enclosed by "("....")" to avoid problem with |
  final public Term term_in_list() throws ParseException {
                            Object o;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 46:
      o = list();
      break;
    case VAR:
    case TK_TRUE:
    case TK_FALSE:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case NUMBER:
    case ATOM:
    case UNNAMEDVAR:
    case 38:
    case 42:
      o = arithm_expr();
      break;
    case STRING:
      o = string();
      break;
    case 30:
      o = plan_term();
      break;
    default:
      jj_la1[42] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                            {if (true) return changeToAtom(o);}
    throw new Error("Missing return statement in function");
  }

/* logical expression */
  final public Object log_expr() throws ParseException {
                              Object t1, t2;
    t1 = log_expr_trm();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 47:
      jj_consume_token(47);
      t2 = log_expr();
                              {if (true) return new LogExpr((LogicalFormula)t1,LogicalOp.or,(LogicalFormula)t2);}
      break;
    default:
      jj_la1[43] = jj_gen;
      ;
    }
                              {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public Object log_expr_trm() throws ParseException {
                              Object t1, t2;
    t1 = log_expr_factor();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 49:
      jj_consume_token(49);
      t2 = log_expr_trm();
                              {if (true) return new LogExpr((LogicalFormula)t1,LogicalOp.and,(LogicalFormula)t2);}
      break;
    default:
      jj_la1[44] = jj_gen;
      ;
    }
                              {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public Object log_expr_factor() throws ParseException {
                                      Object t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TK_NOT:
      jj_consume_token(TK_NOT);
      t = log_expr_factor();
                                      {if (true) return new LogExpr(LogicalOp.not,(LogicalFormula)t);}
      break;
    case VAR:
    case TK_TRUE:
    case TK_FALSE:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case NUMBER:
    case STRING:
    case ATOM:
    case UNNAMEDVAR:
    case 38:
    case 42:
      t = rel_expr();
                                      {if (true) return t;}
      break;
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/* relational expression 
   used in context, body and term
   
     <VAR>      [ <OPREL> <EXP> ]  --> this method returns the VarTerm
   | <LITERAL>  [ <OPREL> <EXP> ]  --> returns the Literal
   | <EXP>      [ <OPREL> <EXP> ]  --> returns the ExprTerm 
*/
  final public Object rel_expr() throws ParseException {
                                             Object op1 = null;
                                             Object op2 = null;
                                             RelationalOp operator = RelationalOp.none;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
    case TK_TRUE:
    case TK_FALSE:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case NUMBER:
    case ATOM:
    case UNNAMEDVAR:
    case 38:
    case 42:
      op1 = arithm_expr();
      break;
    case STRING:
      op1 = string();
      break;
    default:
      jj_la1[46] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 50:
        jj_consume_token(50);
                                             operator = RelationalOp.lt;
        break;
      case 51:
        jj_consume_token(51);
                                             operator = RelationalOp.lte;
        break;
      case 52:
        jj_consume_token(52);
                                             operator = RelationalOp.gt;
        break;
      case 53:
        jj_consume_token(53);
                                             operator = RelationalOp.gte;
        break;
      case 54:
        jj_consume_token(54);
                                             operator = RelationalOp.eq;
        break;
      case 55:
        jj_consume_token(55);
                                             operator = RelationalOp.dif;
        break;
      case 56:
        jj_consume_token(56);
                                             operator = RelationalOp.unify;
        break;
      case 57:
        jj_consume_token(57);
                                             operator = RelationalOp.literalBuilder;
        break;
      default:
        jj_la1[47] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
      case TK_TRUE:
      case TK_FALSE:
      case TK_NEG:
      case TK_BEGIN:
      case TK_END:
      case NUMBER:
      case ATOM:
      case UNNAMEDVAR:
      case 38:
      case 42:
        op2 = arithm_expr();
        break;
      case STRING:
        op2 = string();
        break;
      case 46:
        op2 = list();
        break;
      case 30:
        op2 = plan_term();
        break;
      default:
        jj_la1[48] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                             if ( ((Term)op1).isInternalAction() && operator != RelationalOp.literalBuilder)
                                                {if (true) throw new ParseException(getSourceRef(op1)+" RelExpr: operand '"+op1+"' can not be an internal action.");}
                                             if ( ((Term)op2).isInternalAction() && operator != RelationalOp.literalBuilder)
                                                {if (true) throw new ParseException(getSourceRef(op2)+" RelExpr: operand '"+op2+"' can not be an internal action.");}
                                             {if (true) return new RelExpr((Term)op1, operator, (Term)op2);}
      break;
    default:
      jj_la1[49] = jj_gen;
      ;
    }
                                             {if (true) return op1;}
    throw new Error("Missing return statement in function");
  }

/* arithmetic expression */
  final public Object arithm_expr() throws ParseException {
                                Object t1, t2; ArithmeticOp op;
    t1 = arithm_expr_trm();
                                op = ArithmeticOp.none;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 37:
    case 38:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 37:
        jj_consume_token(37);
                                op = ArithmeticOp.plus;
        break;
      case 38:
        jj_consume_token(38);
                                op = ArithmeticOp.minus;
        break;
      default:
        jj_la1[50] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      t2 = arithm_expr();
                                if (!(t1 instanceof NumberTerm)) {
                                   {if (true) throw new ParseException(getSourceRef(t1)+" ArithExpr: first operand '"+t1+"' is not numeric or variable.");}
                                }
                                if (!(t2 instanceof NumberTerm)) {
                                   {if (true) throw new ParseException(getSourceRef(t2)+" ArithExpr: second operand '"+t2+"' is not numeric or variable.");}
                                }
                                {if (true) return new ArithExpr((NumberTerm)t1, op, (NumberTerm)t2);}
      break;
    default:
      jj_la1[51] = jj_gen;
      ;
    }
                                {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public Object arithm_expr_trm() throws ParseException {
                                  Object t1, t2; ArithmeticOp op;
    t1 = arithm_expr_factor();
                                  op = ArithmeticOp.none;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TK_INTDIV:
    case TK_INTMOD:
    case 58:
    case 59:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 58:
        jj_consume_token(58);
                                  op = ArithmeticOp.times;
        break;
      case 59:
        jj_consume_token(59);
                                  op = ArithmeticOp.div;
        break;
      case TK_INTDIV:
        jj_consume_token(TK_INTDIV);
                                  op = ArithmeticOp.intdiv;
        break;
      case TK_INTMOD:
        jj_consume_token(TK_INTMOD);
                                  op = ArithmeticOp.mod;
        break;
      default:
        jj_la1[52] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      t2 = arithm_expr_trm();
                                  if (!(t1 instanceof NumberTerm)) {
                                    {if (true) throw new ParseException(getSourceRef(t1)+" ArithTerm: first operand '"+t1+"' is not numeric or variable.");}
                                  }
                                  if (!(t2 instanceof NumberTerm)) {
                                    {if (true) throw new ParseException(getSourceRef(t2)+" ArithTerm: second operand '"+t2+"' is not numeric or variable.");}
                                  }
                                  {if (true) return new ArithExpr((NumberTerm)t1, op, (NumberTerm)t2);}
      break;
    default:
      jj_la1[53] = jj_gen;
      ;
    }
                                  {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public Object arithm_expr_factor() throws ParseException {
                                  Object t1, t2; ArithmeticOp op;
    t1 = arithm_expr_simple();
                                  op = ArithmeticOp.none;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 60:
      jj_consume_token(60);
                                  op = ArithmeticOp.pow;
      t2 = arithm_expr_factor();
                                  if (!(t1 instanceof NumberTerm)) {
                                    {if (true) throw new ParseException(getSourceRef(t1)+" ArithFactor: first operand '"+t1+"' is not numeric or variable.");}
                                  }
                                  if (!(t2 instanceof NumberTerm)) {
                                    {if (true) throw new ParseException(getSourceRef(t2)+" ArithFactor: second operand '"+t2+"' is not numeric or variable.");}
                                  }
                                  {if (true) return new ArithExpr((NumberTerm)t1, op, (NumberTerm)t2);}
      break;
    default:
      jj_la1[54] = jj_gen;
      ;
    }
                                  {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  final public Object arithm_expr_simple() throws ParseException {
                                  Token K; Object t; VarTerm v;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
      K = jj_consume_token(NUMBER);
                                  NumberTerm ni = ASSyntax.parseNumber(K.image);
                                  ni.setSrcInfo(new SourceInfo(asSource, K.beginLine));
                                  {if (true) return ni;}
      break;
    case 38:
      jj_consume_token(38);
      t = arithm_expr_simple();
                                  if (!(t instanceof NumberTerm)) {
                                    {if (true) throw new ParseException(getSourceRef(t)+" The argument '"+t+"' of operator '-' is not numeric or variable.");}
                                  }
                                  {if (true) return new ArithExpr(ArithmeticOp.minus, (NumberTerm)t);}
      break;
    case 42:
      jj_consume_token(42);
      t = log_expr();
      jj_consume_token(43);
                                  {if (true) return t;}
      break;
    case VAR:
    case UNNAMEDVAR:
      v = var();
                                  {if (true) return v;}
      break;
    case TK_TRUE:
    case TK_FALSE:
    case TK_NEG:
    case TK_BEGIN:
    case TK_END:
    case ATOM:
      t = function();
                                  {if (true) return t;}
      break;
    default:
      jj_la1[55] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Term function() throws ParseException {
                            Literal l;
    l = literal();
                            ArithFunction af = getArithFunction(l);
                            if (af == null) {
                               {if (true) return l;}
                            } else {
                               ArithFunctionTerm at = new ArithFunctionTerm(af);
                               at.setSrcInfo(l.getSrcInfo());
                               at.setTerms(l.getTerms());
                               at.setAgent(curAg);
                               {if (true) return at;}
                            }
    throw new Error("Missing return statement in function");
  }

  final public VarTerm var() throws ParseException {
                      Token K; VarTerm v; ListTerm lt;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      K = jj_consume_token(VAR);
                      v = new VarTerm(K.image); v.setSrcInfo(new SourceInfo(asSource, K.beginLine));
      break;
    case UNNAMEDVAR:
      K = jj_consume_token(UNNAMEDVAR);
                      v = new UnnamedVar(K.image);
      break;
    default:
      jj_la1[56] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 46:
      lt = list();
                      v.setAnnots(lt);
      break;
    default:
      jj_la1[57] = jj_gen;
      ;
    }
                      {if (true) return v;}
    throw new Error("Missing return statement in function");
  }

  final public StringTerm string() throws ParseException {
                      Token k; StringTermImpl s;
    k = jj_consume_token(STRING);
                      s = new StringTermImpl(k.image.substring(1,k.image.length()-1));
                      s.setSrcInfo(new SourceInfo(asSource,k.beginLine));
                      {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  final private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) return true;
    }
    }
    xsp = jj_scanpos;
    if (jj_3R_18()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_19()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3R_20()) jj_scanpos = xsp;
    return false;
  }

  final private boolean jj_3R_89() {
    if (jj_3R_90()) return true;
    return false;
  }

  final private boolean jj_3R_52() {
    if (jj_scan_token(TK_FALSE)) return true;
    return false;
  }

  final private boolean jj_3R_51() {
    if (jj_scan_token(TK_TRUE)) return true;
    return false;
  }

  final private boolean jj_3R_68() {
    if (jj_3R_77()) return true;
    return false;
  }

  final private boolean jj_3R_67() {
    if (jj_3R_76()) return true;
    return false;
  }

  final private boolean jj_3R_66() {
    if (jj_3R_75()) return true;
    return false;
  }

  final private boolean jj_3R_65() {
    if (jj_3R_74()) return true;
    return false;
  }

  final private boolean jj_3R_60() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_62() {
    if (jj_scan_token(TK_NEG)) return true;
    return false;
  }

  final private boolean jj_3R_30() {
    if (jj_3R_44()) return true;
    return false;
  }

  final private boolean jj_3R_29() {
    if (jj_3R_43()) return true;
    return false;
  }

  final private boolean jj_3R_42() {
    if (jj_scan_token(40)) return true;
    return false;
  }

  final private boolean jj_3R_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_62()) jj_scanpos = xsp;
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_83() {
    if (jj_3R_89()) return true;
    return false;
  }

  final private boolean jj_3R_41() {
    if (jj_scan_token(34)) return true;
    return false;
  }

  final private boolean jj_3R_43() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) return true;
    }
    return false;
  }

  final private boolean jj_3R_27() {
    if (jj_scan_token(39)) return true;
    return false;
  }

  final private boolean jj_3R_26() {
    if (jj_scan_token(38)) return true;
    return false;
  }

  final private boolean jj_3R_25() {
    if (jj_scan_token(37)) return true;
    return false;
  }

  final private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) return true;
    }
    }
    xsp = jj_scanpos;
    if (jj_3R_28()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) return true;
    }
    return false;
  }

  final private boolean jj_3R_78() {
    if (jj_3R_83()) return true;
    return false;
  }

  final private boolean jj_3R_49() {
    if (jj_scan_token(TK_LABEL_AT)) return true;
    return false;
  }

  final private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) jj_scanpos = xsp;
    if (jj_3R_15()) return true;
    return false;
  }

  final private boolean jj_3R_47() {
    if (jj_3R_60()) return true;
    return false;
  }

  final private boolean jj_3R_33() {
    if (jj_scan_token(41)) return true;
    return false;
  }

  final private boolean jj_3R_32() {
    if (jj_scan_token(36)) return true;
    return false;
  }

  final private boolean jj_3R_81() {
    if (jj_3R_79()) return true;
    return false;
  }

  final private boolean jj_3R_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) return true;
    }
    return false;
  }

  final private boolean jj_3R_16() {
    if (jj_scan_token(35)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3R_39() {
    if (jj_scan_token(34)) return true;
    return false;
  }

  final private boolean jj_3R_80() {
    if (jj_3R_78()) return true;
    return false;
  }

  final private boolean jj_3R_14() {
    if (jj_scan_token(TK_LABEL_AT)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3_2() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_14()) jj_scanpos = xsp;
    if (jj_3R_15()) return true;
    xsp = jj_scanpos;
    if (jj_3R_16()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_17()) jj_scanpos = xsp;
    return false;
  }

  final private boolean jj_3R_73() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) return true;
    }
    return false;
  }

  final private boolean jj_3R_35() {
    if (jj_scan_token(30)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) jj_scanpos = xsp;
    if (jj_scan_token(31)) return true;
    return false;
  }

  final private boolean jj_3R_38() {
    if (jj_3R_43()) return true;
    return false;
  }

  final private boolean jj_3R_64() {
    if (jj_3R_73()) return true;
    return false;
  }

  final private boolean jj_3R_63() {
    if (jj_scan_token(TK_NOT)) return true;
    return false;
  }

  final private boolean jj_3R_56() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) return true;
    }
    return false;
  }

  final private boolean jj_3R_88() {
    if (jj_scan_token(38)) return true;
    return false;
  }

  final private boolean jj_3R_87() {
    if (jj_scan_token(37)) return true;
    return false;
  }

  final private boolean jj_3R_86() {
    if (jj_scan_token(40)) return true;
    return false;
  }

  final private boolean jj_3R_45() {
    if (jj_3R_56()) return true;
    return false;
  }

  final private boolean jj_3R_85() {
    if (jj_scan_token(44)) return true;
    return false;
  }

  final private boolean jj_3R_84() {
    if (jj_scan_token(34)) return true;
    return false;
  }

  final private boolean jj_3R_82() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_84()) {
    jj_scanpos = xsp;
    if (jj_3R_85()) {
    jj_scanpos = xsp;
    if (jj_3R_86()) {
    jj_scanpos = xsp;
    if (jj_3R_87()) {
    jj_scanpos = xsp;
    if (jj_3R_88()) return true;
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_77() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_82()) jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3R_31() {
    if (jj_3R_45()) return true;
    return false;
  }

  final private boolean jj_3_1() {
    if (jj_scan_token(TK_BEGIN)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(31)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  final private boolean jj_3R_37() {
    if (jj_scan_token(30)) return true;
    return false;
  }

  final private boolean jj_3R_72() {
    if (jj_3R_35()) return true;
    return false;
  }

  final private boolean jj_3R_71() {
    if (jj_3R_79()) return true;
    return false;
  }

  final private boolean jj_3R_70() {
    if (jj_3R_78()) return true;
    return false;
  }

  final private boolean jj_3R_69() {
    if (jj_3R_36()) return true;
    return false;
  }

  final private boolean jj_3R_61() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_69()) {
    jj_scanpos = xsp;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_76() {
    if (jj_scan_token(TK_WHILE)) return true;
    return false;
  }

  final private boolean jj_3R_79() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  final private boolean jj_3R_55() {
    if (jj_3R_36()) return true;
    return false;
  }

  final private boolean jj_3R_48() {
    if (jj_3R_61()) return true;
    return false;
  }

  final private boolean jj_3R_54() {
    if (jj_scan_token(UNNAMEDVAR)) return true;
    return false;
  }

  final private boolean jj_3R_36() {
    if (jj_scan_token(46)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_48()) jj_scanpos = xsp;
    if (jj_scan_token(48)) return true;
    return false;
  }

  final private boolean jj_3R_53() {
    if (jj_scan_token(VAR)) return true;
    return false;
  }

  final private boolean jj_3R_44() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3R_55()) jj_scanpos = xsp;
    return false;
  }

  final private boolean jj_3R_75() {
    if (jj_scan_token(TK_FOR)) return true;
    return false;
  }

  final private boolean jj_3R_59() {
    if (jj_3R_31()) return true;
    return false;
  }

  final private boolean jj_3R_58() {
    if (jj_3R_35()) return true;
    return false;
  }

  final private boolean jj_3R_57() {
    if (jj_3R_36()) return true;
    return false;
  }

  final private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_96() {
    if (jj_3R_43()) return true;
    return false;
  }

  final private boolean jj_3R_24() {
    if (jj_3R_40()) return true;
    return false;
  }

  final private boolean jj_3R_34() {
    if (jj_3R_46()) return true;
    return false;
  }

  final private boolean jj_3R_95() {
    if (jj_3R_96()) return true;
    return false;
  }

  final private boolean jj_3R_94() {
    if (jj_3R_44()) return true;
    return false;
  }

  final private boolean jj_3R_93() {
    if (jj_scan_token(42)) return true;
    return false;
  }

  final private boolean jj_3R_23() {
    if (jj_3R_39()) return true;
    return false;
  }

  final private boolean jj_3R_20() {
    if (jj_3R_36()) return true;
    return false;
  }

  final private boolean jj_3R_92() {
    if (jj_scan_token(38)) return true;
    return false;
  }

  final private boolean jj_3R_22() {
    if (jj_3R_38()) return true;
    return false;
  }

  final private boolean jj_3R_19() {
    if (jj_3R_35()) return true;
    return false;
  }

  final private boolean jj_3R_74() {
    if (jj_scan_token(TK_IF)) return true;
    return false;
  }

  final private boolean jj_3R_91() {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  final private boolean jj_3R_21() {
    if (jj_3R_37()) return true;
    return false;
  }

  final private boolean jj_3R_18() {
    if (jj_scan_token(42)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  final private boolean jj_3R_90() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_91()) {
    jj_scanpos = xsp;
    if (jj_3R_92()) {
    jj_scanpos = xsp;
    if (jj_3R_93()) {
    jj_scanpos = xsp;
    if (jj_3R_94()) {
    jj_scanpos = xsp;
    if (jj_3R_95()) return true;
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_13() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_21()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_22()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_23()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_24()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(0)) return true;
    return false;
  }

  public as2jTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[58];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x40000000,0x80cb00,0x40000000,0x0,0x40000000,0x10000,0x80cb00,0x40000000,0x80c000,0x0,0x10000,0x0,0x0,0x0,0x0,0x0,0x180cb80,0x1facf80,0x0,0x1facf80,0x40000,0x40040000,0x0,0x0,0x0,0x10000,0x0,0x0,0x0,0x1facf80,0x800,0x80cb00,0x80c000,0x0,0x40000000,0x0,0x0,0x41e0cf80,0x0,0x1000080,0x0,0x41e0cb80,0x41e0cb80,0x0,0x0,0x1e0cf80,0x1e0cb80,0x0,0x41e0cb80,0x0,0x0,0x0,0x3000,0x3000,0x0,0x1a0cb80,0x1000080,0x0,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x4,0x0,0xe0,0x0,0x0,0x0,0x1,0x0,0x8,0x10,0xe0,0x104,0x104,0x0,0x1564,0x200,0x1564,0x0,0x0,0x20,0x1164,0x1164,0x0,0x8,0x210,0x210,0x1564,0x0,0x0,0x0,0x400,0x0,0x4000,0x2000,0x4440,0x2000,0x4000,0x8000,0x4440,0x4440,0x8000,0x20000,0x440,0x440,0x3fc0000,0x4440,0x3fc0000,0x60,0x60,0xc000000,0xc000000,0x10000000,0x440,0x0,0x4000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public as2j(java.io.InputStream stream) {
     this(stream, null);
  }
  public as2j(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new as2jTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public as2j(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new as2jTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public as2j(as2jTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(as2jTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[61];
    for (int i = 0; i < 61; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 58; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 61; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

  }
