/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libopentld4j_OpenTLD4j */

#ifndef _Included_libopentld4j_OpenTLD4j
#define _Included_libopentld4j_OpenTLD4j
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libopentld4j_OpenTLD4j
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_libopentld4j_OpenTLD4j_init
  (JNIEnv *, jclass);

/*
 * Class:     libopentld4j_OpenTLD4j
 * Method:    trackOneFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_libopentld4j_OpenTLD4j_trackOneFrame
  (JNIEnv *, jclass);

/*
 * Class:     libopentld4j_OpenTLD4j
 * Method:    done
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_libopentld4j_OpenTLD4j_done
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
